mshv_vtl/tdx: Fix arm64 build
Add ifdef and define to fix arm64 build.

drivers/hv/mshv_vtl_main.c: In function ‘mshv_tdx_setup_halt_timer’:
drivers/hv/mshv_vtl_main.c:1163:15: error: implicit declaration of function ‘rdtsc’ [-Werror=implicit-function-declaration]
 1163 |         now = rdtsc();
      |               ^~~~~
drivers/hv/mshv_vtl_main.c:1170:73: error: ‘tsc_khz’ undeclared (first use in this function)
 1170 |                 time = mul_u64_u64_div_u64(deadline - now, 1000 * 1000, tsc_khz);
      |                                                                         ^~~~~~~
drivers/hv/mshv_vtl_main.c:1170:73: note: each undeclared identifier is reported only once for each function it appears in
drivers/hv/mshv_vtl_main.c: In function ‘mshv_vtl_switch_to_vtl0_irqoff’:
drivers/hv/mshv_vtl_main.c:1242:49: error: ‘MSHV_VTL_RUN_FLAG_HALTED’ undeclared (first use in this function)
 1242 |         armed = mshv_tdx_halt_timer_pre(flags & MSHV_VTL_RUN_FLAG_HALTED);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

Fixes: fc1601f6e4db ("mshv_vtl/tdx: Arm per-cpu timer to wake up from L0 HLT emulation")
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>